# Generated by Django 5.2.4 on 2025-08-14 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service', models.CharField(choices=[('container_reception', 'Прием груженых и порожних контейнеров'), ('documents_clearance', 'Раскредитовка документов на станции'), ('container_delivery', 'Доставка контейнеров автотранспортом'), ('loading_unloading', 'Организация погрузки-выгрузки'), ('container_storage', 'Хранение контейнеров на терминале'), ('container_shipping', 'Отправка контейнеров по России/экспорт'), ('shipping_docs', 'Оформление перевозочных документов'), ('cargo_insurance', 'Страхование грузов')], max_length=50, verbose_name='Услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Общество с ограниченной ответственностью "Трансагентство"', max_length=200, verbose_name='Полное наименование')),
                ('short_name', models.CharField(default='ООО «ТрА»', max_length=100, verbose_name='Краткое наименование')),
                ('legal_address', models.TextField(default='РТ, 422772, м. р-н Пестречинский, с.п. Кощаковское, д.Званка, ул.Лазурная д.2А', verbose_name='Юридический адрес')),
                ('postal_address', models.TextField(default='РТ, 422772, м. р-н Пестречинский, с.п. Кощаковское, д.Званка, ул.Лазурная д.2А', verbose_name='Почтовый адрес')),
                ('phone', models.CharField(default='+7 (904) 768-70-89', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='tra.info@mail.ru', max_length=254, verbose_name='Эл. почта')),
                ('inn', models.CharField(default='1651092275', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(default='168601001', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(default='1221600078809', max_length=15, verbose_name='ОГРН')),
                ('okpo', models.CharField(default='75376496', max_length=10, verbose_name='ОКПО')),
                ('railway_code', models.CharField(default='4231', max_length=10, verbose_name='Код жд')),
                ('els_code', models.CharField(default='1006546099', max_length=15, verbose_name='Код ЕЛС')),
                ('bank_name_rub', models.CharField(default='ФИЛИАЛ «НИЖЕГОРОДСКИЙ» АО «АЛЬФА-БАНК»', max_length=200, verbose_name='Банк (руб)')),
                ('account_rub', models.CharField(default='40702810629140008516', max_length=20, verbose_name='Рублёвый р/с')),
                ('corr_account_rub', models.CharField(default='30101810200000000824', max_length=20, verbose_name='Корр. счёт (руб)')),
                ('bik_rub', models.CharField(default='042202824', max_length=9, verbose_name='БИК (руб)')),
                ('bank_name_curr', models.CharField(default='ООО Банк Аверс', max_length=200, verbose_name='Банк (вал)')),
                ('account_curr', models.CharField(default='4070216300390000051', max_length=20, verbose_name='Валютный счёт')),
                ('corr_account_curr', models.CharField(default='30101810500000000774', max_length=20, verbose_name='Корр. счёт (вал)')),
                ('bik_curr', models.CharField(default='049205774', max_length=9, verbose_name='БИК (вал)')),
                ('director', models.CharField(default='Давлетшина Алсу Ринатовна', max_length=100, verbose_name='Генеральный директор')),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
    ]
