# Generated by Django 5.2.4 on 2025-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('pending', 'В ожидании')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
