# Generated by Django 5.2.4 on 2025-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default=1, help_text='Этот текст будет отображаться в списке новостей', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Полный текст новости'),
        ),
    ]
